/*=============================================================================
 main_analysis.do
 -----------------------------------------------------------------------------
 Reproduces the regression tables of the paper.

 Two reproduction paths are supported:
   Path A (shipped data):  data_anonymized/product_master.dta
                           -> direct reproduction of the paper's regressions.
   Path B (full pipeline): data/processed/product_master.dta
                           -> generated by running
                              scripts_stata_prep/prepare_stata_data.py
                              after the user supplies their own data.

 The script automatically picks Path A if available; otherwise it falls back
 to Path B. If neither file exists, the script exits with an error.

 Output files (written to stata/output/):
   T1_descriptive.rtf       Descriptive statistics
   T1B_correlations.rtf     Pearson correlation matrix
   T3_main_mediation.rtf    Main 4-column mediation              (paper Table 5)
   T4_indirect_effects.rtf  Bootstrapped indirect effects        (paper Table 6)
   T7_decomposition.rtf     Dimensional decomposition (12 mediators, paper Table 7)
   T6_decomp_pvalues.csv    Raw b-path p-values consumed by
                            scripts_stata_prep/fdr_correction.py
   T9A_robust_N185.rtf      Robustness: N=185 subsample          (paper Table 9 Panel A)

 Sections:
   [Part 0] Load data and construct control variables
   [Part 1] Descriptive statistics + correlations + VIF
   [Part 2] Main mediation 4-column regression
   [Part 3] SEM + bootstrap of 14 indirect effects
   [Part 4] Dimensional decomposition over ME1-5 + MF1-7
   [Part 5] Hand-off to Python BH-FDR correction
   [Part 6] Robustness: N=185 subsample
=============================================================================*/

version 18
clear all
set more off
set seed 42
capture log close
* Run this do-file from the repository root. Example: cd "path/to/repository"

capture mkdir "stata/output"
log using "stata/main_analysis.log", replace text


*==============================================================================
* Part 0. Load data and construct control variables
*==============================================================================
* Pick the shipped anonymized dataset first; fall back to the user pipeline output.
capture confirm file "data_anonymized/product_master.dta"
if !_rc {
    local MASTER "data_anonymized/product_master.dta"
}
else {
    capture confirm file "data/processed/product_master.dta"
    if !_rc {
        local MASTER "data/processed/product_master.dta"
    }
    else {
        display as error "ERROR: product_master.dta not found in data_anonymized/ or data/processed/."
        display as error "Either ship the anonymized dataset under data_anonymized/, or"
        display as error "run scripts_stata_prep/prepare_stata_data.py to produce data/processed/."
        exit 198
    }
}
display "Loading master data from: `MASTER'"

use "`MASTER'", clear

display "Sample size N = " _N

* Construct control variables
gen lnprice    = ln(price + 1)
gen lnreviews  = ln(n_reviews_total + 1)
label var lnprice   "ln(Price)"
label var lnreviews "ln(N_reviews)"

* Main analysis subsample flag
gen included_main = (n_reviews_total >= 20)
label var included_main "Main analysis (N=185)"

* Variable labels used by esttab in the output tables
label var z_pc1 "PC1 Minimalist Lightness"
label var z_pc2 "PC2 Refined Tech-Modern"
label var z_pc3 "PC3 Non-Lifting Premium"
label var z_pc4 "PC4 Heavy Rack Architecture"
label var z_pc5 "PC5 Dark Rough Texture"
label var z_pc6 "PC6 Leg-Style Variation"
label var z_pc7 "PC7 Light-Wood Accessory"
label var m_e_avg "M_E (Kansei composite)"
label var m_f_avg "M_F (Function composite)"
label var y_50_50 "Y satisfaction"

egen id = group(product_id)

* NOTE: the modified dataset is NOT saved back to disk, to avoid corrupting the
* shipped data. Labels and the id column live in memory for this run only, and
* all subsequent Parts operate on the in-memory dataset (no re-`use`).


*==============================================================================
* Part 1. Descriptive statistics + correlations + VIF
*==============================================================================
** 1.1 Descriptive statistics
sum y_50_50 m_e_avg m_f_avg z_pc1 z_pc2 z_pc3 z_pc4 z_pc5 z_pc6 z_pc7 ///
    lnprice lnreviews

* Export Table 1
estpost tabstat y_50_50 m_e_avg m_f_avg z_pc1-z_pc7 lnprice lnreviews, ///
    stats(N mean sd min p50 max) columns(statistics)
esttab using "stata/output/T1_descriptive.rtf", replace ///
    cells("mean(fmt(3)) sd(fmt(3)) min(fmt(3)) p50(fmt(3)) max(fmt(3))") ///
    nonumber nomtitle nonote label ///
    title("Table 1. Descriptive Statistics (N=200)")

** 1.2 Correlation matrix
estpost correlate y_50_50 m_e_avg m_f_avg z_pc1-z_pc7, matrix
esttab using "stata/output/T1B_correlations.rtf", replace ///
    unstack not noobs nonumber compress label ///
    title("Table 1B. Pearson Correlations") b(%6.3f)

** 1.3 VIF
reg y_50_50 z_pc1-z_pc7 m_e_avg m_f_avg lnprice lnreviews
estat vif
* VIF is inspected by hand and reported in the appendix; not exported.


*==============================================================================
* Part 2. Main mediation 4-column regression (paper Table 5)
*==============================================================================
global X "z_pc1 z_pc2 z_pc3 z_pc4 z_pc5 z_pc6 z_pc7"
global M_E "m_e_avg"
global M_F "m_f_avg"
global Y "y_50_50"
global CTRL "lnprice lnreviews"

** (1) a-path: X -> M_E
reg $M_E $X $CTRL, vce(robust)
est store m1_aE

** (2) a-path: X -> M_F
reg $M_F $X $CTRL, vce(robust)
est store m2_aF

** (3) c-path (total effect)
reg $Y $X $CTRL, vce(robust)
est store m3_total

** (4) c' + b path (full model)
reg $Y $X $M_E $M_F $CTRL, vce(robust)
est store m4_full

** Export Table 3
esttab m1_aE m2_aF m3_total m4_full ///
    using "stata/output/T3_main_mediation.rtf", replace ///
    b(%6.3f) t(%6.2f) star(* 0.10 ** 0.05 *** 0.01) ///
    scalar(N r2 r2_a F) compress nogaps label ///
    mtitles("M_E (a-path)" "M_F (a-path)" "Y total (c)" "Y full (c'+b)") ///
    title("Table 3. Main Mediation Analysis (N=200)") ///
    addnote("Robust SE in parentheses." ///
            "*** p<0.01, ** p<0.05, * p<0.10")

esttab m1_aE m2_aF m3_total m4_full, ///
    b(%6.3f) t(%6.2f) star(* 0.10 ** 0.05 *** 0.01) ///
    scalar(N r2 r2_a F) compress nogaps ///
    mtitles("M_E" "M_F" "Y_total" "Y_full")


*==============================================================================
* Part 3. SEM + bootstrap of 14 indirect effects (paper Table 6)
*==============================================================================
** 3.1 SEM estimates all paths in one shot
sem (m_e_avg <- $X $CTRL) ///
    (m_f_avg <- $X $CTRL) ///
    (y_50_50 <- $X m_e_avg m_f_avg $CTRL), ///
    vce(robust)
est store sem_main

** 3.2 Direct / indirect / total effects
estat teffects, compact nogroup

** 3.3 Bootstrap of 14 indirect effects with 95% CI (BCa, 5000 reps)
* Note: bootstrap is slow; 200 obs x 5000 reps takes roughly 5-10 minutes.
bootstrap ///
    indE_pc1 = (_b[m_e_avg:z_pc1] * _b[y_50_50:m_e_avg]) ///
    indE_pc2 = (_b[m_e_avg:z_pc2] * _b[y_50_50:m_e_avg]) ///
    indE_pc3 = (_b[m_e_avg:z_pc3] * _b[y_50_50:m_e_avg]) ///
    indE_pc4 = (_b[m_e_avg:z_pc4] * _b[y_50_50:m_e_avg]) ///
    indE_pc5 = (_b[m_e_avg:z_pc5] * _b[y_50_50:m_e_avg]) ///
    indE_pc6 = (_b[m_e_avg:z_pc6] * _b[y_50_50:m_e_avg]) ///
    indE_pc7 = (_b[m_e_avg:z_pc7] * _b[y_50_50:m_e_avg]) ///
    indF_pc1 = (_b[m_f_avg:z_pc1] * _b[y_50_50:m_f_avg]) ///
    indF_pc2 = (_b[m_f_avg:z_pc2] * _b[y_50_50:m_f_avg]) ///
    indF_pc3 = (_b[m_f_avg:z_pc3] * _b[y_50_50:m_f_avg]) ///
    indF_pc4 = (_b[m_f_avg:z_pc4] * _b[y_50_50:m_f_avg]) ///
    indF_pc5 = (_b[m_f_avg:z_pc5] * _b[y_50_50:m_f_avg]) ///
    indF_pc6 = (_b[m_f_avg:z_pc6] * _b[y_50_50:m_f_avg]) ///
    indF_pc7 = (_b[m_f_avg:z_pc7] * _b[y_50_50:m_f_avg]), ///
    reps(5000) seed(42): ///
    sem (m_e_avg <- $X $CTRL) ///
        (m_f_avg <- $X $CTRL) ///
        (y_50_50 <- $X m_e_avg m_f_avg $CTRL)

est store boot_indirect
estat bootstrap, all

* Bootstrap CI matrices (for downstream inspection)
matrix B_boot = e(b)
matrix V_boot = e(V_modelbased)

esttab boot_indirect using "stata/output/T4_indirect_effects.rtf", replace ///
    b(%7.4f) ci(%7.4f) star(* 0.10 ** 0.05 *** 0.01) ///
    title("Table 4. Indirect Effects (5000 Bootstrap, 95% CI)") ///
    label nonotes


*==============================================================================
* Part 4. Dimensional decomposition over ME1-5 + MF1-7 (paper Table 7)
*==============================================================================
** 4.1 Full model: Y on X + 12 mediators
reg y_50_50 $X me1_z me2_z me3_z me4_z me5_z mf1_z mf2_z mf3_z mf4_z mf5_z mf6_z mf7_z $CTRL, ///
    vce(robust)
est store m5_decomp

esttab m5_decomp using "stata/output/T7_decomposition.rtf", replace ///
    b(%6.3f) t(%6.2f) star(* 0.10 ** 0.05 *** 0.01) ///
    scalar(N r2 r2_a F) compress nogaps label ///
    title("Table 7. Dimensional Decomposition (12 mediators, N=200)") ///
    addnote("Robust SE. Raw p-values; FDR correction applied separately.")

** 4.2 Export b-path p-values for Python FDR
capture file close fh
file open fh using "stata/output/T6_decomp_pvalues.csv", write replace
file write fh "mediator,b,se,t,p_raw" _n
foreach m in me1_z me2_z me3_z me4_z me5_z ///
              mf1_z mf2_z mf3_z mf4_z mf5_z mf6_z mf7_z {
    scalar b_val = _b[`m']
    scalar se_val = _se[`m']
    scalar t_val = b_val / se_val
    scalar p_val = 2 * (1 - normal(abs(t_val)))
    file write fh "`m'," %9.6f (b_val) "," %9.6f (se_val) "," ///
                   %9.6f (t_val) "," %9.6f (p_val) _n
}
file close fh
display "P-values exported to stata/output/T6_decomp_pvalues.csv"
display "Next: python scripts_stata_prep/fdr_correction.py"


*==============================================================================
* Part 5. (Python post-processing: BH-FDR)
*==============================================================================
display ""
display "FDR correction: python scripts_stata_prep/fdr_correction.py"


*==============================================================================
* Part 6. Robustness: N=185 subsample (paper Table 9 Panel A)
*==============================================================================
* This part destructively subsets the sample; it runs last.
keep if included_main == 1
display "Subsample N = " _N

reg $M_E $X $CTRL, vce(robust)
est store r1_aE
reg $M_F $X $CTRL, vce(robust)
est store r2_aF
reg $Y $X $CTRL, vce(robust)
est store r3_total
reg $Y $X $M_E $M_F $CTRL, vce(robust)
est store r4_full

esttab r1_aE r2_aF r3_total r4_full ///
    using "stata/output/T9A_robust_N185.rtf", replace ///
    b(%6.3f) t(%6.2f) star(* 0.10 ** 0.05 *** 0.01) ///
    scalar(N r2 r2_a F) compress nogaps label ///
    mtitles("M_E" "M_F" "Y total" "Y full") ///
    title("Table 9A. Robustness: N=185 (n_reviews>=20)")


*==============================================================================
* Wrap up
*==============================================================================
log close
display ""
display "=========================================="
display "  Done. All outputs in stata/output/"
display "=========================================="
display ""
display "Output tables:"
display "  T1_descriptive.rtf       Descriptive statistics"
display "  T1B_correlations.rtf     Correlation matrix"
display "  T3_main_mediation.rtf    Main mediation (4 columns)"
display "  T4_indirect_effects.rtf  Bootstrap indirect effects"
display "  T7_decomposition.rtf     Dimensional decomposition"
display "  T6_decomp_pvalues.csv    Raw p-values (-> fdr_correction.py)"
display "  T9A_robust_N185.rtf      Robustness: N=185 subsample"
