"""
run_mf_complete_robustness.py
===============================
Complete robustness analysis for functional-evaluation coding.

Decomposes the functional mediator (MF) into evaluative direction
(polarity), discussion intensity, and mention coverage, then tests
whether the negative functional-satisfaction association holds
under each alternative operationalization.

Primary outcome: platform favorable rate (source-separated).
Controls: full seven-variable specification.

Inputs (generated by the extraction pipeline; not shipped with the
public dataset — users must supply their own):
  data/extraction/llm_function_extractions.parquet
  data/extraction/product_function_scores.csv
  lexicons/degree_words.json

Inputs (shipped):
  data_anonymized/product_master.csv

Output:
  diagnostics/  (CSVs and formatted Markdown tables)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor


ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent

# Pipeline outputs — generated by scripts_extraction/, not shipped publicly.
EXTRACTIONS = ROOT / "data" / "extraction" / "llm_function_extractions.parquet"
N_REVIEWS    = ROOT / "data" / "extraction" / "product_function_scores.csv"

# Shipped data and lexicons.
MASTER  = ROOT / "data_anonymized" / "product_master.csv"
DEGREES = ROOT / "lexicons" / "degree_words.json"

DIMENSION_MAP = {
    "升降功能": "MF1", "噪音控制": "MF2", "稳定性承重": "MF3",
    "材质做工": "MF4", "异味环保": "MF5", "操控智能": "MF6", "空间尺寸": "MF7",
}

PC_VARS = [f"z_pc{i}_s" for i in range(1, 8)]
CONTROL_VARS = [
    "lnprice_s", "lnreviews_s", "has_discount_s", "free_shipping_s",
    "ln_imperfection_s", "ln_brand_avg_price_s", "recency_inv_s",
]
BASE_X = PC_VARS + CONTROL_VARS
Y_VAR = "y_favrate_only_s"
ME_VAR = "m_e_avg_s"
MAIN_MF_VAR = "m_f_avg_s"
BOOT_REPS = 5000
BOOT_SEED = 20260716


def normalize_product_id(value):
    return str(value).replace("—", "-").replace("–", "-").strip()


def zscore_observed(series, ddof=0):
    numeric = pd.to_numeric(series, errors="coerce")
    mean = numeric.mean(skipna=True)
    sd = numeric.std(skipna=True, ddof=ddof)
    if not np.isfinite(sd) or sd == 0:
        out = pd.Series(np.nan, index=numeric.index, dtype=float)
        out.loc[numeric.notna()] = 0.0
        return out
    return (numeric - mean) / sd


def robust_ols(data, outcome, predictors):
    used = data[[outcome] + predictors].dropna().copy()
    x = sm.add_constant(used[predictors], has_constant="add")
    fitted = sm.OLS(used[outcome], x).fit(cov_type="HC1", use_t=True)
    return fitted, used.index


def vif_summary(data, predictors):
    used = data[predictors].dropna()
    x = sm.add_constant(used, has_constant="add")
    vals = {}
    for idx, name in enumerate(x.columns):
        if name == "const":
            continue
        vals[name] = float(variance_inflation_factor(x.to_numpy(), idx))
    return vals


def p_stars(p):
    if p < 0.01: return "***"
    if p < 0.05: return "**"
    if p < 0.10: return "*"
    return ""


def format_coef(beta, p):
    if not np.isfinite(beta): return "—"
    return f"{beta:.3f}{p_stars(p)}"


def format_t(t_value):
    if not np.isfinite(t_value): return ""
    return f"({t_value:.2f})"


def dataframe_to_markdown(frame):
    safe = frame.fillna("").astype(str).apply(
        lambda col: col.str.replace("|", "\\|", regex=False))
    header = "| " + " | ".join(safe.columns) + " |"
    separator = "| " + " | ".join(["---"] * len(safe.columns)) + " |"
    body = ["| " + " | ".join(row) + " |" for row in safe.to_numpy().tolist()]
    return "\n".join([header, separator] + body)


def build_metrics():
    with DEGREES.open("r", encoding="utf-8") as fh:
        degree_lookup = json.load(fh)["weight_lookup"]

    matches = pd.read_parquet(EXTRACTIONS)
    matches["product_id"] = matches["product_id"].map(normalize_product_id)
    matches["commentId"] = matches["commentId"].astype(str)
    matches = matches[matches["dimension"].isin(DIMENSION_MAP)].copy()
    matches["dimension_code"] = matches["dimension"].map(DIMENSION_MAP)

    def degree_weight(value):
        if value is None or (isinstance(value, float) and np.isnan(value)):
            return 0.8
        token = str(value).strip()
        if not token: return 0.8
        return float(degree_lookup.get(token, 0.8))

    matches["degree_weight"] = matches["degree_word"].map(degree_weight)
    matches["final_value"] = (
        pd.to_numeric(matches["polarity"], errors="coerce") * matches["degree_weight"])

    comment_dimension = matches.groupby(
        ["product_id", "commentId", "dimension_code"], as_index=False)["final_value"].mean()

    n_reviews = pd.read_csv(N_REVIEWS, dtype={"product_id": str})[["product_id", "n_reviews"]]
    n_reviews["product_id"] = n_reviews["product_id"].map(normalize_product_id)
    n_reviews = n_reviews.rename(columns={"n_reviews": "N_total"})
    metrics = n_reviews.copy()

    any_mentions = matches.groupby("product_id")["commentId"].nunique().rename(
        "n_reviews_any_function").reset_index()
    metrics = metrics.merge(any_mentions, on="product_id", how="left")
    metrics["n_reviews_any_function"] = metrics["n_reviews_any_function"].fillna(0)
    metrics["mf_coverage_any_raw"] = metrics["n_reviews_any_function"] / metrics["N_total"]

    dimension_diagnostics = []
    density_z_columns = []; polarity_z_columns = []
    intensity_z_columns = []; coverage_z_columns = []; abs_density_z_columns = []

    for dim in [f"MF{i}" for i in range(1, 8)]:
        sub = comment_dimension[comment_dimension["dimension_code"] == dim]
        grouped = sub.groupby("product_id")["final_value"].agg(
            sum_signed="sum", H="count", conditional_polarity="mean",
            sum_absolute=lambda x: x.abs().sum(),
            conditional_intensity=lambda x: x.abs().mean()).reset_index()
        grouped = n_reviews.merge(grouped, on="product_id", how="left")
        grouped["H"] = grouped["H"].fillna(0)
        grouped["sum_signed"] = grouped["sum_signed"].fillna(0)
        grouped["sum_absolute"] = grouped["sum_absolute"].fillna(0)
        grouped.loc[grouped["H"] == 0, ["conditional_polarity", "conditional_intensity"]] = np.nan

        grouped[f"{dim}_density_raw"] = grouped["sum_signed"] / grouped["N_total"]
        grouped[f"{dim}_abs_density_raw"] = grouped["sum_absolute"] / grouped["N_total"]
        grouped[f"{dim}_coverage_raw"] = grouped["H"] / grouped["N_total"]
        grouped[f"{dim}_polarity_raw"] = grouped["conditional_polarity"]
        grouped[f"{dim}_intensity_raw"] = grouped["conditional_intensity"]
        grouped[f"{dim}_density_z"] = zscore_observed(grouped[f"{dim}_density_raw"], ddof=0)
        grouped[f"{dim}_abs_density_z"] = zscore_observed(grouped[f"{dim}_abs_density_raw"], ddof=0)
        grouped[f"{dim}_polarity_z_strict"] = zscore_observed(grouped[f"{dim}_polarity_raw"], ddof=0)
        grouped[f"{dim}_intensity_z_strict"] = zscore_observed(grouped[f"{dim}_intensity_raw"], ddof=0)
        grouped[f"{dim}_coverage_z"] = zscore_observed(grouped[f"{dim}_coverage_raw"], ddof=0)

        keep = ["product_id", f"{dim}_density_raw", f"{dim}_abs_density_raw",
                f"{dim}_coverage_raw", f"{dim}_polarity_raw", f"{dim}_intensity_raw",
                f"{dim}_density_z", f"{dim}_abs_density_z", f"{dim}_polarity_z_strict",
                f"{dim}_intensity_z_strict", f"{dim}_coverage_z"]
        metrics = metrics.merge(grouped[keep], on="product_id", how="left")
        density_z_columns.append(f"{dim}_density_z")
        abs_density_z_columns.append(f"{dim}_abs_density_z")
        polarity_z_columns.append(f"{dim}_polarity_z_strict")
        intensity_z_columns.append(f"{dim}_intensity_z_strict")
        coverage_z_columns.append(f"{dim}_coverage_z")
        dimension_diagnostics.append({
            "dimension": dim, "products_with_match": int((grouped["H"] > 0).sum()),
            "products_without_match": int((grouped["H"] == 0).sum()),
            "matched_review_dimension_cells": int(grouped["H"].sum()),
            "mean_dimension_coverage": float(grouped[f"{dim}_coverage_raw"].mean()),
            "mean_conditional_polarity": float(grouped[f"{dim}_polarity_raw"].mean()),
            "mean_conditional_intensity": float(grouped[f"{dim}_intensity_raw"].mean())})

    metrics["mf_density_reconstructed_raw"] = metrics[density_z_columns].mean(axis=1)
    metrics["mf_abs_density_balanced_raw"] = metrics[abs_density_z_columns].mean(axis=1)
    metrics["mf_polarity_strict_raw"] = metrics[polarity_z_columns].mean(axis=1, skipna=True)
    metrics["mf_intensity_strict_raw"] = metrics[intensity_z_columns].mean(axis=1, skipna=True)
    metrics["mf_coverage_balanced_raw"] = metrics[coverage_z_columns].mean(axis=1)
    metrics["n_dimensions_observed"] = metrics[polarity_z_columns].notna().sum(axis=1)
    metrics.loc[metrics["n_dimensions_observed"] == 0,
                ["mf_polarity_strict_raw", "mf_intensity_strict_raw"]] = np.nan

    pooled = comment_dimension.groupby("product_id")["final_value"].agg(
        pooled_H="count", mf_polarity_pooled_raw="mean",
        mf_intensity_pooled_raw=lambda x: x.abs().mean(),
        pooled_sum_signed="sum").reset_index()
    metrics = metrics.merge(pooled, on="product_id", how="left")
    metrics["pooled_H"] = metrics["pooled_H"].fillna(0)
    metrics["mf_match_frequency_raw"] = metrics["pooled_H"] / metrics["N_total"]
    metrics["mf_signed_match_density_raw"] = metrics["pooled_sum_signed"].fillna(0) / metrics["N_total"]

    final_raw = {
        "mf_density_reconstructed_s": "mf_density_reconstructed_raw",
        "mf_abs_density_balanced_s": "mf_abs_density_balanced_raw",
        "mf_polarity_strict_s": "mf_polarity_strict_raw",
        "mf_intensity_strict_s": "mf_intensity_strict_raw",
        "mf_coverage_any_s": "mf_coverage_any_raw",
        "mf_coverage_balanced_s": "mf_coverage_balanced_raw",
        "mf_polarity_pooled_s": "mf_polarity_pooled_raw",
        "mf_intensity_pooled_s": "mf_intensity_pooled_raw",
        "mf_match_frequency_s": "mf_match_frequency_raw",
    }
    for standardized, raw in final_raw.items():
        metrics[standardized] = zscore_observed(metrics[raw], ddof=1)

    master = pd.read_csv(MASTER, dtype={"product_id": str})
    master["product_id"] = master["product_id"].map(normalize_product_id)
    analysis = master.merge(metrics, on="product_id", how="left", validate="1:1")

    runtime_standardization = {
        "has_discount_s": "has_discount", "free_shipping_s": "free_shipping",
        "ln_imperfection_s": "ln_imperfection",
        "ln_brand_avg_price_s": "ln_brand_avg_price", "recency_inv_s": "recency_inv"}
    for standardized, raw in runtime_standardization.items():
        analysis[standardized] = zscore_observed(analysis[raw], ddof=1)

    crosscheck = {
        "n_products": int(len(analysis)),
        "products_with_any_function_match": int((analysis["mf_coverage_any_raw"] > 0).sum()),
        "products_without_any_function_match": int((analysis["mf_coverage_any_raw"] == 0).sum()),
        "strict_polarity_missing_products": int(analysis["mf_polarity_strict_s"].isna().sum()),
        "strict_intensity_missing_products": int(analysis["mf_intensity_strict_s"].isna().sum()),
        "max_abs_reconstructed_density_error": float(
            (analysis["mf_density_reconstructed_raw"] - analysis["m_f_avg"]).abs().max()),
        "mean_any_mention_coverage": float(analysis["mf_coverage_any_raw"].mean())}
    return analysis, pd.DataFrame(dimension_diagnostics), crosscheck


def fit_models(analysis):
    model_specs = {
        "M1_main_density": [MAIN_MF_VAR],
        "M2_strict_polarity": ["mf_polarity_strict_s"],
        "M3_polarity_intensity": ["mf_polarity_strict_s", "mf_intensity_strict_s"],
        "M4_polarity_coverage": ["mf_polarity_strict_s", "mf_coverage_any_s"],
        "M5_full_decomposition": ["mf_polarity_strict_s", "mf_intensity_strict_s", "mf_coverage_any_s"],
        "S1_legacy_abs_density": ["mf_polarity_strict_s", "mf_abs_density_balanced_s"],
        "S2_pooled_full": ["mf_polarity_pooled_s", "mf_intensity_pooled_s", "mf_coverage_any_s"],
    }
    rows = []; fitted_models = {}
    for model_name, focal_vars in model_specs.items():
        predictors = PC_VARS + [ME_VAR] + focal_vars + CONTROL_VARS
        fitted, used_index = robust_ols(analysis, Y_VAR, predictors)
        fitted_models[model_name] = fitted
        vifs = vif_summary(analysis.loc[used_index], predictors)
        for var in focal_vars + [ME_VAR]:
            rows.append({
                "model": model_name, "variable": var,
                "beta": float(fitted.params[var]), "robust_se_hc1": float(fitted.bse[var]),
                "t": float(fitted.tvalues[var]), "p": float(fitted.pvalues[var]),
                "ci95_low": float(fitted.conf_int().loc[var, 0]),
                "ci95_high": float(fitted.conf_int().loc[var, 1]),
                "N": int(fitted.nobs), "r2": float(fitted.rsquared),
                "adj_r2": float(fitted.rsquared_adj),
                "max_vif": float(max(vifs.values())), "variable_vif": float(vifs[var])})
    return pd.DataFrame(rows), fitted_models, model_specs


def fit_a_paths(analysis):
    mediators = [MAIN_MF_VAR, "mf_polarity_strict_s", "mf_intensity_strict_s", "mf_coverage_any_s"]
    rows = []
    for mediator in mediators:
        fitted, _ = robust_ols(analysis, mediator, BASE_X)
        for pc in PC_VARS:
            rows.append({
                "mediator": mediator, "pc": pc,
                "beta": float(fitted.params[pc]), "robust_se_hc1": float(fitted.bse[pc]),
                "t": float(fitted.tvalues[pc]), "p": float(fitted.pvalues[pc]),
                "N": int(fitted.nobs), "r2": float(fitted.rsquared), "adj_r2": float(fitted.rsquared_adj)})
    return pd.DataFrame(rows)


def percentile_summary(draws, point):
    low = np.quantile(draws, 0.025, axis=0)
    high = np.quantile(draws, 0.975, axis=0)
    p_low = (np.sum(draws <= 0, axis=0) + 1) / (draws.shape[0] + 1)
    p_high = (np.sum(draws >= 0, axis=0) + 1) / (draws.shape[0] + 1)
    p_two = np.minimum(1.0, 2 * np.minimum(p_low, p_high))
    return point, low, high, p_two


def bootstrap_indirect_effects(analysis):
    rng = np.random.default_rng(BOOT_SEED)
    rows = []
    main_cols = [Y_VAR, ME_VAR, MAIN_MF_VAR] + BASE_X
    main = analysis[main_cols].dropna().reset_index(drop=True)
    xa_main = sm.add_constant(main[BASE_X], has_constant="add").to_numpy()
    xb_main_cols = PC_VARS + [ME_VAR, MAIN_MF_VAR] + CONTROL_VARS
    xb_main = sm.add_constant(main[xb_main_cols], has_constant="add").to_numpy()
    y_main = main[Y_VAR].to_numpy()
    m_main = main[MAIN_MF_VAR].to_numpy()
    beta_a_main = np.linalg.lstsq(xa_main, m_main, rcond=None)[0]
    beta_b_main = np.linalg.lstsq(xb_main, y_main, rcond=None)[0]
    pc_a_positions = np.arange(1, 8)
    b_density_position = 1 + xb_main_cols.index(MAIN_MF_VAR)
    point_main = beta_a_main[pc_a_positions] * beta_b_main[b_density_position]
    draws_main = np.empty((BOOT_REPS, 7))
    for b in range(BOOT_REPS):
        idx = rng.integers(0, len(main), len(main))
        ba = np.linalg.lstsq(xa_main[idx], m_main[idx], rcond=None)[0]
        bb = np.linalg.lstsq(xb_main[idx], y_main[idx], rcond=None)[0]
        draws_main[b] = ba[pc_a_positions] * bb[b_density_position]
    point, low, high, p_two = percentile_summary(draws_main, point_main)
    for i, pc in enumerate(PC_VARS):
        rows.append({"specification": "main_density", "pc": pc, "component": "signed_density",
                      "estimate": float(point[i]), "bootstrap_ci95_low": float(low[i]),
                      "bootstrap_ci95_high": float(high[i]), "bootstrap_p_two_sided": float(p_two[i]),
                      "bootstrap_reps": BOOT_REPS, "N": len(main)})

    components = ["mf_polarity_strict_s", "mf_intensity_strict_s", "mf_coverage_any_s"]
    full_cols = [Y_VAR, ME_VAR] + components + BASE_X
    full = analysis[full_cols].dropna().reset_index(drop=True)
    xa = sm.add_constant(full[BASE_X], has_constant="add").to_numpy()
    mediator_matrix = full[components].to_numpy()
    xb_cols = PC_VARS + [ME_VAR] + components + CONTROL_VARS
    xb = sm.add_constant(full[xb_cols], has_constant="add").to_numpy()
    y = full[Y_VAR].to_numpy()
    beta_a = np.linalg.lstsq(xa, mediator_matrix, rcond=None)[0]
    beta_b = np.linalg.lstsq(xb, y, rcond=None)[0]
    component_b_positions = [1 + xb_cols.index(c) for c in components]
    point_components = beta_a[pc_a_positions, :] * beta_b[component_b_positions][None, :]
    point_total = point_components.sum(axis=1)
    draws_components = np.empty((BOOT_REPS, 7, 3))
    for b in range(BOOT_REPS):
        idx = rng.integers(0, len(full), len(full))
        ba = np.linalg.lstsq(xa[idx], mediator_matrix[idx], rcond=None)[0]
        bb = np.linalg.lstsq(xb[idx], y[idx], rcond=None)[0]
        draws_components[b] = ba[pc_a_positions, :] * bb[component_b_positions][None, :]
    component_labels = ["conditional_polarity", "conditional_intensity", "coverage"]
    for c_idx, component in enumerate(component_labels):
        point, low, high, p_two = percentile_summary(draws_components[:, :, c_idx], point_components[:, c_idx])
        for i, pc in enumerate(PC_VARS):
            rows.append({"specification": "full_decomposition", "pc": pc, "component": component,
                          "estimate": float(point[i]), "bootstrap_ci95_low": float(low[i]),
                          "bootstrap_ci95_high": float(high[i]), "bootstrap_p_two_sided": float(p_two[i]),
                          "bootstrap_reps": BOOT_REPS, "N": len(full)})
    point, low, high, p_two = percentile_summary(draws_components.sum(axis=2), point_total)
    for i, pc in enumerate(PC_VARS):
        rows.append({"specification": "full_decomposition", "pc": pc, "component": "total_functional",
                      "estimate": float(point[i]), "bootstrap_ci95_low": float(low[i]),
                      "bootstrap_ci95_high": float(high[i]), "bootstrap_p_two_sided": float(p_two[i]),
                      "bootstrap_reps": BOOT_REPS, "N": len(full)})
    return pd.DataFrame(rows)


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    analysis, dimension_diagnostics, crosscheck = build_metrics()
    model_results, _, model_specs = fit_models(analysis)
    a_paths = fit_a_paths(analysis)
    indirect = bootstrap_indirect_effects(analysis)

    focal_components = ["mf_polarity_strict_s", "mf_intensity_strict_s", "mf_coverage_any_s",
                        "mf_abs_density_balanced_s", "mf_polarity_pooled_s", "mf_intensity_pooled_s"]
    correlations = analysis[focal_components].corr().reset_index().rename(columns={"index": "variable"})

    analysis.to_csv(OUT / "mf_complete_product_metrics.csv", index=False, encoding="utf-8-sig")
    dimension_diagnostics.to_csv(OUT / "mf_dimension_match_diagnostics.csv", index=False, encoding="utf-8-sig")
    model_results.to_csv(OUT / "mf_model_results.csv", index=False, encoding="utf-8-sig")
    a_paths.to_csv(OUT / "mf_a_path_results.csv", index=False, encoding="utf-8-sig")
    indirect.to_csv(OUT / "mf_indirect_bootstrap_5000.csv", index=False, encoding="utf-8-sig")
    correlations.to_csv(OUT / "mf_component_correlations.csv", index=False, encoding="utf-8-sig")

    metadata = {"outcome": "standardized logit platform favorable rate only",
                "bootstrap_reps": BOOT_REPS, "bootstrap_seed": BOOT_SEED,
                "robust_covariance": "HC1", "model_specs": model_specs,
                "crosscheck": crosscheck}
    (OUT / "mf_analysis_metadata.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(crosscheck, ensure_ascii=False, indent=2))
    print(f"\nOutputs written to {OUT}")


if __name__ == "__main__":
    main()
